[2019-04-08 14:32:47,718 INFO root] Taurus CLI Tool v1.13.4
[2019-04-08 14:32:47,719 DEBUG root] Command-line options: {'log': '/var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/bzt_9t1hbxji.log', 'option': None, 'quiet': None, 'verbose': None, 'no_system_configs': None, 'aliases': []}
[2019-04-08 14:32:47,719 DEBUG root] Python: CPython 3.7.3
[2019-04-08 14:32:47,719 DEBUG root] OS: uname_result(system='Darwin', node='amirhosein-mac.local', release='17.5.0', version='Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64', machine='x86_64', processor='i386')
[2019-04-08 14:32:47,720 INFO root] Starting with configs: ['allRequests.json']
[2019-04-08 14:32:47,721 DEBUG root] Using personal config: /Users/apple/.bzt-rc
[2019-04-08 14:32:47,721 INFO Engine] Configuring...
[2019-04-08 14:32:47,824 DEBUG Engine] Base configs list: ['/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml']
[2019-04-08 14:32:47,825 DEBUG Engine.Configuration] Configs: ['/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml']
[2019-04-08 14:32:47,825 DEBUG Engine.Configuration] Reading /usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml as YAML
[2019-04-08 14:32:47,949 DEBUG Engine] User configs list: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 14:32:47,950 DEBUG Engine.Configuration] Configs: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 14:32:47,966 DEBUG Engine.Configuration] Reading /Users/apple/.bzt-rc as YAML
[2019-04-08 14:32:47,985 DEBUG Engine.Configuration] Reading allRequests.json as YAML
[2019-04-08 14:32:47,999 DEBUG Engine.Configuration] Configs: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 14:32:48,000 DEBUG Engine.Configuration] Reading /Users/apple/.bzt-rc as YAML
[2019-04-08 14:32:48,016 DEBUG Engine.Configuration] Reading allRequests.json as YAML
[2019-04-08 14:32:48,031 DEBUG Engine] Requesting updates info: https://gettaurus.org/updates/?version=1.13.4&installID=macos-3c075440e027
[2019-04-08 14:32:48,032 DEBUG HTTPClient] Making HTTP request GET https://gettaurus.org/updates/?version=1.13.4&installID=macos-3c075440e027
[2019-04-08 14:32:48,036 INFO Engine] Artifacts dir: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442
[2019-04-08 14:32:48,038 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective
[2019-04-08 14:32:48,045 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.yml
[2019-04-08 14:32:48,047 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): gettaurus.org:443
[2019-04-08 14:32:48,127 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.json
[2019-04-08 14:32:48,131 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/merged.yml
[2019-04-08 14:32:48,132 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/merged.yml
[2019-04-08 14:32:48,140 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/merged.json
[2019-04-08 14:32:48,141 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/merged.json
[2019-04-08 14:32:48,142 DEBUG Engine] Add existing artifact (move=False): allRequests.json
[2019-04-08 14:32:48,143 DEBUG Engine] Copying allRequests.json to /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/allRequests.json
[2019-04-08 14:32:48,147 DEBUG root] Closing log handler: /var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/bzt_9t1hbxji.log
[2019-04-08 14:32:48,149 DEBUG root] Switched writing logs to /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/bzt.log
[2019-04-08 14:32:48,149 DEBUG root] Linting config
[2019-04-08 14:32:48,157 INFO Engine] Preparing...
[2019-04-08 14:32:48,158 DEBUG Engine] Module config: consolidator {'class': 'bzt.modules.aggregator.ConsolidatingAggregator'}
[2019-04-08 14:32:48,160 DEBUG root] Importing module: bzt.modules.aggregator
[2019-04-08 14:32:48,953 DEBUG urllib3.connectionpool] https://gettaurus.org:443 "GET /updates/?version=1.13.4&installID=macos-3c075440e027 HTTP/1.1" 403 1587
[2019-04-08 14:32:48,973 DEBUG Engine] Failed to check for updates: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 697, in _check_updates
    data = response.json()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2019-04-08 14:32:48,973 WARNING Engine] Failed to check for updates
[2019-04-08 14:32:48,995 DEBUG root] Loading class: 'ConsolidatingAggregator' from <module 'bzt.modules.aggregator' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/aggregator.py'>
[2019-04-08 14:32:48,996 DEBUG Engine.consolidator] Buffer scaling setup: percentile 95.0 from [0.0, 50.0, 90.0, 95.0, 99.0, 99.9, 100.0] selected
[2019-04-08 14:32:48,996 DEBUG Engine] Module config: monitoring {'class': 'bzt.modules.monitoring.Monitoring'}
[2019-04-08 14:32:48,997 DEBUG root] Importing module: bzt.modules.monitoring
[2019-04-08 14:32:49,002 DEBUG root] Loading class: 'Monitoring' from <module 'bzt.modules.monitoring' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/monitoring.py'>
[2019-04-08 14:32:49,003 DEBUG Engine] Module config: local {'class': 'bzt.modules.provisioning.Local'}
[2019-04-08 14:32:49,003 DEBUG root] Importing module: bzt.modules.provisioning
[2019-04-08 14:32:49,004 DEBUG root] Loading class: 'Local' from <module 'bzt.modules.provisioning' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/provisioning.py'>
[2019-04-08 14:32:49,004 DEBUG Engine] Module config: jmeter {'class': 'bzt.modules.jmeter.JMeterExecutor', 'protocol-handlers': {'http': 'bzt.jmx.http.HTTPProtocolHandler'}, 'plugins': ['jpgc-casutg', 'jpgc-dummy', 'jpgc-ffw', 'jpgc-fifo', 'jpgc-functions', 'jpgc-json', 'jpgc-perfmon', 'jpgc-prmctl', 'jpgc-tst'], 'properties': {'jmeter.save.saveservice.autoflush': 'true', 'jmeter.save.saveservice.connect_time': 'true', 'jmeterengine.force.system.exit': 'true', 'summariser.name': ''}}
[2019-04-08 14:32:49,004 DEBUG root] Importing module: bzt.modules.jmeter
[2019-04-08 14:32:49,050 DEBUG root] Loading class: 'JMeterExecutor' from <module 'bzt.modules.jmeter' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/jmeter.py'>
[2019-04-08 14:32:49,050 DEBUG Engine.local] Preparing executor: jmeter/4519676672
[2019-04-08 14:32:49,051 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter.log
[2019-04-08 14:32:49,051 DEBUG Engine.jmeter] Checking if port 4445 is free
[2019-04-08 14:32:49,053 DEBUG Engine.jmeter] Port 4445 is free
[2019-04-08 14:32:49,053 DEBUG Engine.jmeter] Using port 4445 for management
[2019-04-08 14:32:49,054 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/requests.jmx
[2019-04-08 14:32:49,059 DEBUG root] Importing module: bzt.jmx.http
[2019-04-08 14:32:49,060 DEBUG root] Loading class: 'HTTPProtocolHandler' from <module 'bzt.jmx.http' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/jmx/http.py'>
[2019-04-08 14:32:49,067 DEBUG JMeterScenarioBuilder] Saving JMX to: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/requests.jmx
[2019-04-08 14:32:49,069 DEBUG Engine.jmeter] Additional system properties {'sun.net.inetaddr.ttl': 0}
[2019-04-08 14:32:49,070 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/system.properties
[2019-04-08 14:32:49,071 DEBUG Engine.jmeter] Additional properties: {'jmeter.save.saveservice.autoflush': 'true', 'jmeter.save.saveservice.connect_time': 'true', 'jmeterengine.force.system.exit': 'true', 'summariser.name': '', 'jmeterengine.nongui.port': 4445, 'jmeterengine.nongui.maxport': 4445, 'jmeter.save.saveservice.timestamp_format': 'ms', 'sampleresult.default.encoding': 'UTF-8', 'user.classpath': '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442:/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442'}
[2019-04-08 14:32:49,072 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter-bzt.properties
[2019-04-08 14:32:49,073 DEBUG Engine.jmeter.JavaVM] Trying JavaVM: ['java', '-version']
[2019-04-08 14:32:49,075 DEBUG root] Executing shell: ['java', '-version'] at .
[2019-04-08 14:32:49,648 DEBUG Engine.jmeter.JavaVM] JavaVM output: 
[2019-04-08 14:32:49,649 DEBUG Engine.jmeter.TclLibrary] We don't need to check tcl library on this platform
[2019-04-08 14:32:49,650 DEBUG Engine.jmeter.JMeter] Trying JMeter..
[2019-04-08 14:32:49,651 DEBUG root] Executing shell: ['/Users/apple/.bzt/jmeter-taurus/5.1.1/bin/jmeter.sh', '-j', '/var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/jmeterjtpuvpw3log', '--version'] at .
[2019-04-08 14:32:53,807 DEBUG Engine.jmeter.JMeter] JMeter check:     _    ____   _    ____ _   _ _____       _ __  __ _____ _____ _____ ____     
   / \  |  _ \ / \  / ___| | | | ____|     | |  \/  | ____|_   _| ____|  _ \   
  / _ \ | |_) / _ \| |   | |_| |  _|    _  | | |\/| |  _|   | | |  _| | |_) | 
 / ___ \|  __/ ___ \ |___|  _  | |___  | |_| | |  | | |___  | | | |___|  _ <  
/_/   \_\_| /_/   \_\____|_| |_|_____|  \___/|_|  |_|_____| |_| |_____|_| \_\ 5.1.1 r1855137  

Copyright (c) 1999-2019 The Apache Software Foundation

 / 
[2019-04-08 14:32:53,814 DEBUG Engine.jmeter] Load: LoadSpec(concurrency=100, throughput=100.0, ramp_up=20.0, hold=30.0, iterations=0, duration=50.0, steps=None)
[2019-04-08 14:32:53,826 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/kpi.jtl
[2019-04-08 14:32:53,829 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/error.jtl
[2019-04-08 14:32:53,838 DEBUG Engine.jmeter.LoadSettingsProcessor.ThreadGroupHandler] Converting ThreadGroup (UserScenario) to ConcurrencyThreadGroup and apply load parameters
[2019-04-08 14:32:53,840 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
[2019-04-08 14:32:53,840 DEBUG JMX] Saving JMX to: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
[2019-04-08 14:32:53,844 DEBUG root] Executing shell: ['/Users/apple/.bzt/jmeter-taurus/5.1.1/bin/PluginsManagerCMD.sh', 'install-for-jmx', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx'] at .
[2019-04-08 14:32:59,807 DEBUG Engine.jmeter.JMeter] Try to detect plugins for /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
2019-04-08 14:32:56,735 INFO o.j.r.PluginManagerCMD: Command is: install-for-jmx
2019-04-08 14:32:57,053 INFO o.j.r.JARSourceHTTP: Found cached repo
2019-04-08 14:32:57,885 INFO o.j.r.PluginManager: Plugins Status: [jpgc-functions=2.1, jpgc-casutg=2.8, jpgc-dummy=0.2, jpgc-ffw=2.0, jpgc-fifo=0.2, jpgc-json=2.7, jpgc-prmctl=0.4, jpgc-perfmon=2.1, jpgc-plugins-manager=1.3, jpgc-tst=2.5, jmeter-core=5.1.1, jmeter-ftp=5.1.1, jmeter-http=5.1.1, jmeter-jdbc=5.1.1, jmeter-jms=5.1.1, jmeter-junit=5.1.1, jmeter-java=5.1.1, jmeter-ldap=5.1.1, jmeter-mail=5.1.1, jmeter-mongodb=5.1.1, jmeter-native=5.1.1, jmeter-tcp=5.1.1, jmeter-components=5.1.1]
2019-04-08 14:32:57,893 INFO o.j.r.PluginManagerCMD: Params line is: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
2019-04-08 14:32:58,937 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2019-04-08 14:32:58,981 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2019-04-08 14:32:58,998 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2019-04-08 14:32:59,118 INFO o.a.j.p.h.c.CacheManager: Will only cache the following methods: [GET]
2019-04-08 14:32:59,124 INFO o.a.j.p.h.c.CookieManager: Settings: Delete null: true Check: true Allow variable: true Save: false Prefix: COOKIE_
2019-04-08 14:32:59,234 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 14:32:59,234 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 14:32:59,235 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 14:32:59,235 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 14:32:59,235 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2019-04-08 14:32:59,235 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2019-04-08 14:32:59,426 INFO o.j.r.PluginManager: Finishing without changes


[2019-04-08 14:32:59,809 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter.out
[2019-04-08 14:32:59,811 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter.err
[2019-04-08 14:32:59,815 DEBUG Engine] Module config: final-stats {'class': 'bzt.modules.reporting.FinalStatus'}
[2019-04-08 14:32:59,816 DEBUG root] Importing module: bzt.modules.reporting
[2019-04-08 14:32:59,861 DEBUG easyprocess] version=0.2.5
[2019-04-08 14:32:59,864 DEBUG pyvirtualdisplay] version=0.2.1
[2019-04-08 14:32:59,869 DEBUG root] Loading class: 'FinalStatus' from <module 'bzt.modules.reporting' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/reporting.py'>
[2019-04-08 14:32:59,870 DEBUG Engine] Module config: console {'class': 'bzt.modules.console.ConsoleStatusReporter'}
[2019-04-08 14:32:59,870 DEBUG root] Importing module: bzt.modules.console
[2019-04-08 14:32:59,870 DEBUG root] Loading class: 'ConsoleStatusReporter' from <module 'bzt.modules.console' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/console.py'>
[2019-04-08 14:32:59,870 WARNING Engine] Module 'console' can be only used once, will merge all new instances into single
[2019-04-08 14:32:59,871 DEBUG Engine] Module config: blazemeter {'class': 'bzt.modules.blazemeter.BlazeMeterUploader'}
[2019-04-08 14:32:59,871 DEBUG root] Importing module: bzt.modules.blazemeter
[2019-04-08 14:32:59,871 DEBUG root] Loading class: 'BlazeMeterUploader' from <module 'bzt.modules.blazemeter' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py'>
[2019-04-08 14:32:59,887 WARNING Engine.blazemeter] No BlazeMeter API key provided, will upload anonymously
[2019-04-08 14:32:59,888 DEBUG Engine.blazemeter] Installing http client
[2019-04-08 14:32:59,888 DEBUG User] Request: GET https://a.blazemeter.com/api/v4/web/version None
[2019-04-08 14:32:59,888 DEBUG HTTPClient] Making HTTP request GET https://a.blazemeter.com/api/v4/web/version
[2019-04-08 14:32:59,894 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): a.blazemeter.com:443
[2019-04-08 14:33:02,247 DEBUG urllib3.connectionpool] https://a.blazemeter.com:443 "GET /api/v4/web/version HTTP/1.1" 200 233
[2019-04-08 14:33:02,251 DEBUG User] Response [200]: {
    "api_version": 4,
    "error": null,
    "result": "blazemeter-php7-backend-package 928 release/2019-04-02_126 137ce603d6f9e3814fbd1ecc2a17af16c5eee191 Thu Apr 4 18:27:30 2019 +0300 137ce603d6f9e3814fbd1ecc2a17af16c5eee191\n"
}
[2019-04-08 14:33:02,255 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.yml
[2019-04-08 14:33:02,286 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.json
[2019-04-08 14:33:02,288 INFO Engine] Starting...
[2019-04-08 14:33:02,289 DEBUG Engine] Startup <bzt.modules.monitoring.Monitoring object at 0x10d2ead30>
[2019-04-08 14:33:02,289 DEBUG Engine] Startup <bzt.modules.aggregator.ConsolidatingAggregator object at 0x10bbe22e8>
[2019-04-08 14:33:02,290 DEBUG Engine] Startup <bzt.modules.reporting.FinalStatus object at 0x10d6bf588>
[2019-04-08 14:33:02,290 DEBUG Engine] Startup <bzt.modules.console.ConsoleStatusReporter object at 0x10d6bfda0>
[2019-04-08 14:33:02,290 INFO Engine.console] Waiting for results...
[2019-04-08 14:33:02,290 DEBUG Engine] Startup <bzt.modules.blazemeter.BlazeMeterUploader object at 0x10d7242e8>
[2019-04-08 14:33:02,290 INFO Engine.blazemeter] Initiating data feeding...
[2019-04-08 14:33:02,290 DEBUG User] Request: POST https://a.blazemeter.com/api/v4/sessions None
[2019-04-08 14:33:02,291 DEBUG HTTPClient] Making HTTP request POST https://a.blazemeter.com/api/v4/sessions
[2019-04-08 14:33:03,239 DEBUG urllib3.connectionpool] https://a.blazemeter.com:443 "POST /api/v4/sessions HTTP/1.1" 201 2844
[2019-04-08 14:33:03,240 DEBUG User] Response [201]: {
    "api_version": 4,
    "error": null,
    "result": {
        "session": {
            "id": "r-ext-5cab1c566b2ab",
            "name": "external",
            "userId": 386483,
            "publicToken": "zFz6hmJmsEutSYI0DgXroc4JkBcez0h4fi5FHqyKLWBmp
[2019-04-08 14:33:03,241 INFO Engine.blazemeter] Started data feeding: https://a.blazemeter.com/app/?public-token=zFz6hmJmsEutSYI0DgXroc4JkBcez0h4fi5FHqyKLWBmpL3hfG#reports/r-ext-5cab1c566b2ab/summary
[2019-04-08 14:33:03,459 DEBUG Engine] Startup <bzt.modules.provisioning.Local object at 0x10bbe2780>
[2019-04-08 14:33:03,461 DEBUG Engine.local] Delay setup for jmeter/UserScenario: 0(start-at) + 0(delay) = 0
[2019-04-08 14:33:03,467 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.yml
[2019-04-08 14:33:03,547 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.json
[2019-04-08 14:33:03,552 DEBUG root] Leveling down log file verbosity to INFO, use -v option to have DEBUG messages enabled
[2019-04-08 14:33:03,553 DEBUG root] Leveled up log file verbosity
[2019-04-08 14:33:03,556 DEBUG root] Executing shell: ['/Users/apple/.bzt/jmeter-taurus/5.1.1/bin/jmeter.sh', '-t', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx', '-j', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter.log', '-q', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/jmeter-bzt.properties', '-n', '-S', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/system.properties'] at /Users/apple/Desktop/bachelorProject/stressThing/StressThing
[2019-04-08 14:33:03,577 DEBUG root] Leveling down log file verbosity to INFO, use -v option to have DEBUG messages enabled
[2019-04-08 14:33:03,824 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:03,982 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:05,749 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:05,795 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:06,740 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:06,775 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:07,760 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:07,834 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:08,758 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:08,792 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:09,753 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:09,794 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:10,756 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:10,803 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:11,757 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:11,852 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:12,766 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:12,805 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:13,727 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:13,762 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:14,785 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:14,841 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:15,797 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:15,854 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:16,896 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:16,953 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:17,794 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:17,828 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:18,846 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:18,893 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:19,862 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:19,916 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:20,823 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:20,962 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:21,866 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:21,911 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:22,880 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:22,924 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:23,770 WARNING Engine.jmeter.JTLReader] No details for errors of PROPERTY: getstatus THING: falldetection, dropped info: [{'cnt': 1, 'msg': 'Non HTTP response message: Connection reset', 'tag': None, 'rc': 'SocketException', 'type': 0, 'urls': Counter()}]
[2019-04-08 14:33:23,770 WARNING Engine.jmeter.JTLReader] No details for errors of , dropped info: [{'cnt': 1, 'msg': 'Non HTTP response message: Connection reset', 'tag': None, 'rc': 'SocketException', 'type': 0, 'urls': Counter()}]
[2019-04-08 14:33:23,907 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:23,951 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:24,752 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:24,781 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:25,820 WARNING Engine.jmeter.JTLReader] No details for errors of ACTION: feedback THING: falldetection, dropped info: [{'cnt': 3, 'msg': 'Non HTTP response message: Connection reset', 'tag': None, 'rc': 'SocketException', 'type': 0, 'urls': Counter()}]
[2019-04-08 14:33:26,209 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:26,249 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:26,757 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:26,783 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:27,774 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:27,797 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:28,782 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:28,844 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:29,794 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:29,829 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:30,791 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:30,819 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:31,794 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:31,832 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:32,804 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:32,831 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:33,796 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:33,823 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:33:34,803 INFO Engine.console] Waiting for finish...
[2019-04-08 14:33:34,833 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:34:05,299 WARNING Engine.blazemeter] Failed to send data, will retry in 30.0 sec...
[2019-04-08 14:34:35,413 ERROR Engine.blazemeter] Fatal error sending data: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Read timed out. (read timeout=30.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Read timed out. (read timeout=30.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 125, in _impl
    method(self, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 490, in __send_data
    self._session.send_kpi_data(serialized, do_check)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 670, in send_kpi_data
    response = self._request(url, data, headers=hdr)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 91, in _request
    response = self.http_request(method=log_method, url=url, data=data, headers=headers, timeout=self.timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
bzt.TaurusNetworkError: Request to https://data.blazemeter.com/submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a75c0>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a75c0>: Failed to establish a new connection: [Errno 65] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a75c0>: Failed to establish a new connection: [Errno 65] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 131, in _impl
    method(self, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 490, in __send_data
    self._session.send_kpi_data(serialized, do_check)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 670, in send_kpi_data
    response = self._request(url, data, headers=hdr)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 91, in _request
    response = self.http_request(method=log_method, url=url, data=data, headers=headers, timeout=self.timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
bzt.TaurusNetworkError: Request to https://data.blazemeter.com/submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 failed

[2019-04-08 14:34:35,428 WARNING Engine.blazemeter] Will skip failed data and continue running
[2019-04-08 14:34:35,467 WARNING Engine.blazemeter] Failed to send data, will retry in 30.0 sec...
[2019-04-08 14:35:35,556 ERROR Engine.blazemeter] Fatal error sending data: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a7080>: Failed to establish a new connection: [Errno 65] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a7080>: Failed to establish a new connection: [Errno 65] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a7080>: Failed to establish a new connection: [Errno 65] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 125, in _impl
    method(self, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 510, in __send_monitoring
    self._session.send_monitoring_data(engine_id, data)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 685, in send_monitoring_data
    self.upload_file(file_name, to_json(data))
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 713, in upload_file
    response = self._request(url, body.form_as_bytes(), headers=hdr)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 91, in _request
    response = self.http_request(method=log_method, url=url, data=data, headers=headers, timeout=self.timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
bzt.TaurusNetworkError: Request to https://data.blazemeter.com/api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a73c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a73c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='data.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e2a73c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 131, in _impl
    method(self, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 510, in __send_monitoring
    self._session.send_monitoring_data(engine_id, data)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 685, in send_monitoring_data
    self.upload_file(file_name, to_json(data))
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 713, in upload_file
    response = self._request(url, body.form_as_bytes(), headers=hdr)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 91, in _request
    response = self.http_request(method=log_method, url=url, data=data, headers=headers, timeout=self.timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
bzt.TaurusNetworkError: Request to https://data.blazemeter.com/api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 failed

[2019-04-08 14:35:35,818 WARNING Engine.blazemeter] Will skip failed data and continue running
[2019-04-08 14:35:36,552 INFO Engine.jmeter.JTLReader] Changed data analysis delay to 3s
[2019-04-08 14:35:36,964 INFO Engine.jmeter.JTLReader] Changed data analysis delay to 150s
[2019-04-08 14:35:37,707 INFO Engine.console] Waiting for finish...
[2019-04-08 14:35:37,774 ERROR Engine.console] Console screen failure: ord() expected string of length 1, but int found
[2019-04-08 14:36:08,441 WARNING Engine.blazemeter] Failed to send data, will retry in 30.0 sec...
[2019-04-08 14:36:28,115 WARNING Engine] Please wait for graceful shutdown...
[2019-04-08 14:36:28,119 DEBUG root] Leveled up log file verbosity
[2019-04-08 14:36:28,120 INFO Engine] Shutting down...
[2019-04-08 14:36:28,120 DEBUG Engine] Current stop reason: 
[2019-04-08 14:36:28,126 DEBUG Engine.local] Shutdown jmeter/UserScenario
[2019-04-08 14:36:29,129 INFO Engine.jmeter] Sending Shutdown command to JMeter on port 4445...
[2019-04-08 14:36:30,131 DEBUG Engine.jmeter] JMeter stopped on Shutdown command
[2019-04-08 14:36:30,134 DEBUG Engine.console] No logger_handler or orig_stream was detected
[2019-04-08 14:36:30,144 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.yml
[2019-04-08 14:36:30,200 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.json
[2019-04-08 14:36:30,202 WARNING root] Keyboard interrupt
[2019-04-08 14:36:30,204 DEBUG root] KeyboardInterrupt: 
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/cli.py", line 258, in perform
    self.engine.run()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 259, in run
    reraise(exc_info, exc_value)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/six/py3.py", line 86, in reraise
    raise exc
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 238, in run
    self._wait()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 280, in _wait
    while not self._check_modules_list():
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 267, in _check_modules_list
    finished = bool(module.check())
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 474, in check
    self.__send_data(self.kpi_buffer)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 130, in _impl
    time.sleep(self._user.timeout)
[2019-04-08 14:36:30,205 INFO Engine] Post-processing...
[2019-04-08 14:36:30,205 DEBUG Engine.local] Post-process jmeter/UserScenario
[2019-04-08 14:36:30,205 DEBUG Engine] Add existing artifact (move=True): /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
[2019-04-08 14:36:30,206 DEBUG Engine] No need to copy /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/modified_requests.jmx
[2019-04-08 14:36:30,208 DEBUG Engine.jmeter.JTLErrorsReader] Read bytes from error file: 35000
[2019-04-08 14:36:30,217 DEBUG Engine.jmeter.JTLReader.IncrementalCSVReader] Read: 10 lines / 2127 bytes (at speed 1048576)
[2019-04-08 14:36:30,218 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,219 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717804 into 1554717807
[2019-04-08 14:36:30,220 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,220 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,220 DEBUG Engine.jmeter.JTLReader] Putting sample 1554717805 into 1554717807
[2019-04-08 14:36:30,220 DEBUG Engine.jmeter.JTLReader] Buffer len: 6; Known errors count: 3
[2019-04-08 14:36:30,221 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717807, 6 in buffer
[2019-04-08 14:36:30,223 DEBUG aggregator] Growing HDR from 76000.0 to 184000.0
[2019-04-08 14:36:30,231 DEBUG aggregator] Growing HDR from 76000.0 to 184000.0
[2019-04-08 14:36:30,244 DEBUG aggregator] Growing HDR from 184000.0 to 185000.0
[2019-04-08 14:36:30,246 DEBUG aggregator] Growing HDR from 76000.0 to 185000.0
[2019-04-08 14:36:30,260 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717807, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', '', 'ACTION: feedback THING: falldetection'])
[2019-04-08 14:36:30,261 DEBUG aggregator] Growing HDR from 76000.0 to 185000.0
[2019-04-08 14:36:30,272 DEBUG aggregator] Growing HDR from 76000.0 to 184000.0
[2019-04-08 14:36:30,282 DEBUG aggregator] Growing HDR from 76000.0 to 185000.0
[2019-04-08 14:36:30,297 DEBUG Engine.jmeter.JTLReader] Buffer len: 5; Known errors count: 3
[2019-04-08 14:36:30,571 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717808, 5 in buffer
[2019-04-08 14:36:30,573 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717808, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', ''])
[2019-04-08 14:36:30,576 DEBUG Engine.jmeter.JTLReader] Buffer len: 4; Known errors count: 3
[2019-04-08 14:36:30,744 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717809, 4 in buffer
[2019-04-08 14:36:30,746 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717809, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', ''])
[2019-04-08 14:36:30,749 DEBUG Engine.jmeter.JTLReader] Buffer len: 3; Known errors count: 3
[2019-04-08 14:36:31,129 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717810, 3 in buffer
[2019-04-08 14:36:31,131 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717810, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', ''])
[2019-04-08 14:36:31,136 DEBUG Engine.jmeter.JTLReader] Buffer len: 2; Known errors count: 3
[2019-04-08 14:36:31,717 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717811, 2 in buffer
[2019-04-08 14:36:31,721 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717811, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', ''])
[2019-04-08 14:36:31,726 DEBUG Engine.jmeter.JTLReader] Buffer len: 1; Known errors count: 3
[2019-04-08 14:36:31,918 DEBUG Engine.jmeter.JTLReader] Aggregating: 1554717812, 1 in buffer
[2019-04-08 14:36:31,920 DEBUG Engine.jmeter.JTLErrorsReader] Got error info for 1554717812, labels: dict_keys(['PROPERTY: getstatus THING: falldetection', ''])
[2019-04-08 14:36:31,925 DEBUG Engine.jmeter.JTLReader] Buffer len: 0; Known errors count: 3
[2019-04-08 14:36:31,925 DEBUG Engine.consolidator] Consolidator buffer[8]: dict_keys([1554717805, 1554717806, 1554717807, 1554717808, 1554717809, 1554717810, 1554717811, 1554717812])
[2019-04-08 14:36:31,925 DEBUG Engine.consolidator] Merging into 1554717805
[2019-04-08 14:36:31,926 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:31,928 DEBUG aggregator] Growing HDR from 5000.0 to 76000.0
[2019-04-08 14:36:31,939 DEBUG aggregator] Growing HDR from 5000.0 to 76000.0
[2019-04-08 14:36:32,690 DEBUG Engine.consolidator] Processed datapoint: 1554717805/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:32,690 DEBUG Engine.consolidator] Merging into 1554717806
[2019-04-08 14:36:32,690 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:32,692 DEBUG aggregator] Growing HDR from 5000.0 to 76000.0
[2019-04-08 14:36:33,343 DEBUG Engine.consolidator] Processed datapoint: 1554717806/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:33,344 DEBUG Engine.consolidator] Merging into 1554717807
[2019-04-08 14:36:33,344 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:33,344 DEBUG aggregator] Growing HDR from 76000.0 to 185000.0
[2019-04-08 14:36:33,356 DEBUG aggregator] Growing HDR from 76000.0 to 184000.0
[2019-04-08 14:36:33,368 DEBUG aggregator] Growing HDR from 76000.0 to 185000.0
[2019-04-08 14:36:33,755 DEBUG Engine.consolidator] Processed datapoint: 1554717807/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:33,755 DEBUG Engine.consolidator] Merging into 1554717808
[2019-04-08 14:36:33,755 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:34,216 DEBUG Engine.consolidator] Processed datapoint: 1554717808/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:34,216 DEBUG Engine.consolidator] Merging into 1554717809
[2019-04-08 14:36:34,216 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:34,801 DEBUG Engine.consolidator] Processed datapoint: 1554717809/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:34,802 DEBUG Engine.consolidator] Merging into 1554717810
[2019-04-08 14:36:34,802 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:35,125 DEBUG Engine.consolidator] Processed datapoint: 1554717810/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:35,126 DEBUG Engine.consolidator] Merging into 1554717811
[2019-04-08 14:36:35,126 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:35,425 DEBUG Engine.consolidator] Processed datapoint: 1554717811/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:35,425 DEBUG Engine.consolidator] Merging into 1554717812
[2019-04-08 14:36:35,425 DEBUG Engine.consolidator] Bypassing consolidation because of single result
[2019-04-08 14:36:35,826 DEBUG Engine.consolidator] Processed datapoint: 1554717812/ConsolidatingAggregator@4491977448
[2019-04-08 14:36:35,826 INFO Engine.final-stats] Test duration: 0:03:28
[2019-04-08 14:36:35,827 INFO Engine.final-stats] Samples count: 551, 35.57% failures
[2019-04-08 14:36:35,827 INFO Engine.final-stats] Average times: total 15.828, latency 0.123, connect 12.414
[2019-04-08 14:36:35,831 INFO Engine.final-stats] Percentiles:
(0lqqqqqqqqqqqqqqqwqqqqqqqqqqqqqqqk(B
(0x(B Percentile, % (0x(B Resp. Time, s (0x(B
(0tqqqqqqqqqqqqqqqnqqqqqqqqqqqqqqqu(B
(0x(B           0.0 (0x(B         0.016 (0x(B
(0x(B          50.0 (0x(B         0.183 (0x(B
(0x(B          90.0 (0x(B        75.136 (0x(B
(0x(B          95.0 (0x(B        75.136 (0x(B
(0x(B          99.0 (0x(B       183.296 (0x(B
(0x(B          99.9 (0x(B        184.32 (0x(B
(0x(B         100.0 (0x(B        184.32 (0x(B
(0mqqqqqqqqqqqqqqqvqqqqqqqqqqqqqqqj(B
[2019-04-08 14:36:35,838 INFO Engine.final-stats] Request label stats:
(0lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqwqqqqqqqqwqqqqqqqqwqqqqqqqqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk(B
(0x(B label                                    (0x(B status (0x(B   succ (0x(B avg_rt (0x(B error                                                                                             (0x(B
(0tqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqnqqqqqqqqnqqqqqqqqnqqqqqqqqnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu(B
(0x(B ACTION: feedback THING: falldetection    (0x(B  FAIL  (0x(B 65.98% (0x(B 11.686 (0x(B Non HTTP response message: Connect to 172.20.10.3:8000 [/172.20.10.3] failed: Operation timed out (0x(B
(0x(B                                          (0x(B        (0x(B        (0x(B        (0x(B Non HTTP response message: Connection reset                                                       (0x(B
(0x(B                                          (0x(B        (0x(B        (0x(B        (0x(B Non HTTP response message: Socket closed                                                          (0x(B
(0x(B PROPERTY: getstatus THING: falldetection (0x(B  FAIL  (0x(B 63.23% (0x(B 19.049 (0x(B Non HTTP response message: Socket closed                                                          (0x(B
(0x(B                                          (0x(B        (0x(B        (0x(B        (0x(B Non HTTP response message: Connect to 172.20.10.3:8000 [/172.20.10.3] failed: Operation timed out (0x(B
(0x(B                                          (0x(B        (0x(B        (0x(B        (0x(B Non HTTP response message: Connection reset                                                       (0x(B
(0mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqvqqqqqqqqvqqqqqqqqvqqqqqqqqvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj(B
[2019-04-08 14:36:35,838 DEBUG Engine.console] No logger_handler or orig_stream was detected
[2019-04-08 14:36:35,838 DEBUG Engine.blazemeter] KPI bulk buffer len in post-proc: 11
[2019-04-08 14:36:35,838 INFO Engine.blazemeter] Sending remaining KPI data to server...
[2019-04-08 14:36:38,145 DEBUG User] Request: POST https://data.blazemeter.com/submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 b'{\n "labels": [\n  {\n   "n": 551,\n   "name": "ALL",\n   "interval": 1,\n   "intervals": [\n    {\n     "ec": 7,\n     "ts": 1554717802,\n     "na": 61,\n     "n": 50,\n     "failed": 7,\n     "rc": [\n      {\n       "n": 43,\n       "f": [],\n       "rc": "200"\n      },'
[2019-04-08 14:36:38,145 DEBUG HTTPClient] Making HTTP request POST https://data.blazemeter.com/submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1
[2019-04-08 14:36:38,159 DEBUG urllib3.connectionpool] Starting new HTTPS connection (6): data.blazemeter.com:443
[2019-04-08 14:36:46,212 DEBUG urllib3.connectionpool] https://data.blazemeter.com:443 "POST /submit.php?session_id=r-ext-5cab1c566b2ab&signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&test_id=6753824&user_id=386483&pq=0&target=labels_bulk&update=1 HTTP/1.1" 200 139
[2019-04-08 14:36:46,215 DEBUG User] Response [200]: {"api_version":2,"error":null,"result":{"session":{"_id":"r-ext-5cab1c566b2ab","name":"external","statusCode":15,"status":"INITIALIZING"}}}
[2019-04-08 14:36:46,234 DEBUG User] Request: POST https://data.blazemeter.com/api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 b'--===============7424162094536511582==\r\nContent-Disposition: file; name="file"; filename="r-ext-5cab1c566b2ab-0-c.monitoring.json"\r\nContent-Type: application/json\r\n\r\n{\n "reportInfo": {\n  "sessionId": "r-ext-5cab1c566b2ab",\n  "timestamp": 1554718006.221557,'
[2019-04-08 14:36:46,236 DEBUG HTTPClient] Making HTTP request POST https://data.blazemeter.com/api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741
[2019-04-08 14:36:46,734 DEBUG urllib3.connectionpool] https://data.blazemeter.com:443 "POST /api/v4/image/r-ext-5cab1c566b2ab/files?signature=ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw&masterId=19303741 HTTP/1.1" 200 116
[2019-04-08 14:36:46,736 DEBUG User] Response [200]: {
    "api_version": 4,
    "error": null,
    "result": [
        "r-ext-5cab1c566b2ab-0-c.monitoring.json"
    ]
}
[2019-04-08 14:36:46,737 DEBUG Engine.blazemeter] Set last check time to: 1554717779.872236
[2019-04-08 14:36:46,737 INFO Engine.blazemeter] Ending data feeding...
[2019-04-08 14:36:46,738 DEBUG User] Request: POST https://a.blazemeter.com/api/v4/sessions/r-ext-5cab1c566b2ab/terminate-external {
 "signature": "ci1leHQtNWNhYjFjNTY2YjJhYjoxNTU1OTI3MzgyOjc1MDI3M2JkZmU2ODcxNmIxODZmODZlYmE3YWI1NTMwY2EzYTRmYWI0M2I4NDZhYTI4Yjc1YTJiYmY4OTU0NTI5ZGEyZDZiZThiNjY1M2VjZDA0ZmIwYmY3MGYwZTljNWIyYjk1ZWE3MGI0YTYyNDk5NWY4ODNmNjA2N2IyN2Qw",
 "testId": 6753824,
 "se
[2019-04-08 14:36:46,738 DEBUG HTTPClient] Making HTTP request POST https://a.blazemeter.com/api/v4/sessions/r-ext-5cab1c566b2ab/terminate-external
[2019-04-08 14:36:46,990 DEBUG urllib3.connectionpool] https://a.blazemeter.com:443 "POST /api/v4/sessions/r-ext-5cab1c566b2ab/terminate-external HTTP/1.1" 200 2076
[2019-04-08 14:36:46,991 DEBUG User] Response [200]: {
    "api_version": 4,
    "error": null,
    "result": {
        "success": "Terminating",
        "session": {
            "id": "r-ext-5cab1c566b2ab",
            "name": "external",
            "userId": 386483,
            "publicToken": "zFz6hmJmsEu
[2019-04-08 14:36:46,992 INFO Engine.blazemeter] Online report link: https://a.blazemeter.com/app/?public-token=zFz6hmJmsEutSYI0DgXroc4JkBcez0h4fi5FHqyKLWBmpL3hfG#reports/r-ext-5cab1c566b2ab/summary
[2019-04-08 14:36:46,997 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.yml
[2019-04-08 14:36:47,059 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/effective.json
[2019-04-08 14:36:47,060 INFO root] Artifacts dir: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442
[2019-04-08 14:36:47,061 WARNING root] Done performing with code: 1
[2019-04-08 14:36:47,061 DEBUG root] Closing log handler: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_14-32-48.033442/bzt.log
