[2019-04-08 12:42:26,970 INFO root] Taurus CLI Tool v1.13.4
[2019-04-08 12:42:26,971 DEBUG root] Command-line options: {'log': '/var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/bzt_gip38kqu.log', 'option': None, 'quiet': None, 'verbose': None, 'no_system_configs': None, 'aliases': []}
[2019-04-08 12:42:26,971 DEBUG root] Python: CPython 3.7.3
[2019-04-08 12:42:26,971 DEBUG root] OS: uname_result(system='Darwin', node='amirhosein-mac.local', release='17.5.0', version='Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64', machine='x86_64', processor='i386')
[2019-04-08 12:42:26,971 INFO root] Starting with configs: ['allRequests.json']
[2019-04-08 12:42:26,972 DEBUG root] Using personal config: /Users/apple/.bzt-rc
[2019-04-08 12:42:26,972 INFO Engine] Configuring...
[2019-04-08 12:42:27,023 DEBUG Engine] Base configs list: ['/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml']
[2019-04-08 12:42:27,023 DEBUG Engine.Configuration] Configs: ['/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml']
[2019-04-08 12:42:27,024 DEBUG Engine.Configuration] Reading /usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/resources/10-base-config.yml as YAML
[2019-04-08 12:42:27,176 DEBUG Engine] User configs list: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 12:42:27,176 DEBUG Engine.Configuration] Configs: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 12:42:27,178 DEBUG Engine.Configuration] Reading /Users/apple/.bzt-rc as YAML
[2019-04-08 12:42:27,199 DEBUG Engine.Configuration] Reading allRequests.json as YAML
[2019-04-08 12:42:27,220 DEBUG Engine.Configuration] Configs: ['/Users/apple/.bzt-rc', 'allRequests.json']
[2019-04-08 12:42:27,222 DEBUG Engine.Configuration] Reading /Users/apple/.bzt-rc as YAML
[2019-04-08 12:42:27,243 DEBUG Engine.Configuration] Reading allRequests.json as YAML
[2019-04-08 12:42:27,272 DEBUG Engine] Requesting updates info: https://gettaurus.org/updates/?version=1.13.4&installID=macos-3c075440e027
[2019-04-08 12:42:27,272 DEBUG HTTPClient] Making HTTP request GET https://gettaurus.org/updates/?version=1.13.4&installID=macos-3c075440e027
[2019-04-08 12:42:27,277 INFO Engine] Artifacts dir: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840
[2019-04-08 12:42:27,279 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/effective
[2019-04-08 12:42:27,286 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/effective.yml
[2019-04-08 12:42:27,288 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): gettaurus.org:443
[2019-04-08 12:42:27,559 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/effective.json
[2019-04-08 12:42:27,563 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/merged.yml
[2019-04-08 12:42:27,564 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/merged.yml
[2019-04-08 12:42:27,576 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/merged.json
[2019-04-08 12:42:27,577 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/merged.json
[2019-04-08 12:42:27,578 DEBUG Engine] Add existing artifact (move=False): allRequests.json
[2019-04-08 12:42:27,579 DEBUG Engine] Copying allRequests.json to /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/allRequests.json
[2019-04-08 12:42:27,582 DEBUG root] Closing log handler: /var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/bzt_gip38kqu.log
[2019-04-08 12:42:27,584 DEBUG root] Switched writing logs to /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/bzt.log
[2019-04-08 12:42:27,584 DEBUG root] Linting config
[2019-04-08 12:42:27,592 INFO Engine] Preparing...
[2019-04-08 12:42:27,594 DEBUG Engine] Module config: consolidator {'class': 'bzt.modules.aggregator.ConsolidatingAggregator'}
[2019-04-08 12:42:27,594 DEBUG root] Importing module: bzt.modules.aggregator
[2019-04-08 12:42:28,211 DEBUG root] Loading class: 'ConsolidatingAggregator' from <module 'bzt.modules.aggregator' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/aggregator.py'>
[2019-04-08 12:42:28,212 DEBUG Engine.consolidator] Buffer scaling setup: percentile 95.0 from [0.0, 50.0, 90.0, 95.0, 99.0, 99.9, 100.0] selected
[2019-04-08 12:42:28,212 DEBUG Engine] Module config: monitoring {'class': 'bzt.modules.monitoring.Monitoring'}
[2019-04-08 12:42:28,213 DEBUG root] Importing module: bzt.modules.monitoring
[2019-04-08 12:42:28,217 DEBUG root] Loading class: 'Monitoring' from <module 'bzt.modules.monitoring' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/monitoring.py'>
[2019-04-08 12:42:28,217 DEBUG Engine] Module config: local {'class': 'bzt.modules.provisioning.Local'}
[2019-04-08 12:42:28,218 DEBUG root] Importing module: bzt.modules.provisioning
[2019-04-08 12:42:28,218 DEBUG root] Loading class: 'Local' from <module 'bzt.modules.provisioning' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/provisioning.py'>
[2019-04-08 12:42:28,218 DEBUG Engine] Module config: jmeter {'class': 'bzt.modules.jmeter.JMeterExecutor', 'protocol-handlers': {'http': 'bzt.jmx.http.HTTPProtocolHandler'}, 'plugins': ['jpgc-casutg', 'jpgc-dummy', 'jpgc-ffw', 'jpgc-fifo', 'jpgc-functions', 'jpgc-json', 'jpgc-perfmon', 'jpgc-prmctl', 'jpgc-tst'], 'properties': {'jmeter.save.saveservice.autoflush': 'true', 'jmeter.save.saveservice.connect_time': 'true', 'jmeterengine.force.system.exit': 'true', 'summariser.name': ''}}
[2019-04-08 12:42:28,218 DEBUG root] Importing module: bzt.modules.jmeter
[2019-04-08 12:42:28,255 DEBUG root] Loading class: 'JMeterExecutor' from <module 'bzt.modules.jmeter' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/jmeter.py'>
[2019-04-08 12:42:28,255 DEBUG Engine.local] Preparing executor: jmeter/4625316384
[2019-04-08 12:42:28,256 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/jmeter.log
[2019-04-08 12:42:28,256 DEBUG Engine.jmeter] Checking if port 4445 is free
[2019-04-08 12:42:28,257 DEBUG Engine.jmeter] Port 4445 is free
[2019-04-08 12:42:28,257 DEBUG Engine.jmeter] Using port 4445 for management
[2019-04-08 12:42:28,258 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/requests.jmx
[2019-04-08 12:42:28,260 DEBUG root] Importing module: bzt.jmx.http
[2019-04-08 12:42:28,261 DEBUG root] Loading class: 'HTTPProtocolHandler' from <module 'bzt.jmx.http' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/jmx/http.py'>
[2019-04-08 12:42:28,265 DEBUG JMeterScenarioBuilder] Saving JMX to: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/requests.jmx
[2019-04-08 12:42:28,266 DEBUG Engine.jmeter] Additional system properties {'sun.net.inetaddr.ttl': 0}
[2019-04-08 12:42:28,266 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/system.properties
[2019-04-08 12:42:28,268 DEBUG Engine.jmeter] Additional properties: {'jmeter.save.saveservice.autoflush': 'true', 'jmeter.save.saveservice.connect_time': 'true', 'jmeterengine.force.system.exit': 'true', 'summariser.name': '', 'jmeterengine.nongui.port': 4445, 'jmeterengine.nongui.maxport': 4445, 'jmeter.save.saveservice.timestamp_format': 'ms', 'sampleresult.default.encoding': 'UTF-8', 'user.classpath': '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840:/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840'}
[2019-04-08 12:42:28,268 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/jmeter-bzt.properties
[2019-04-08 12:42:28,270 DEBUG Engine.jmeter.JavaVM] Trying JavaVM: ['java', '-version']
[2019-04-08 12:42:28,271 DEBUG root] Executing shell: ['java', '-version'] at .
[2019-04-08 12:42:28,878 DEBUG Engine.jmeter.JavaVM] JavaVM output: 
[2019-04-08 12:42:28,879 DEBUG Engine.jmeter.TclLibrary] We don't need to check tcl library on this platform
[2019-04-08 12:42:28,879 DEBUG Engine.jmeter.JMeter] Trying JMeter..
[2019-04-08 12:42:28,882 DEBUG root] Executing shell: ['/Users/apple/.bzt/jmeter-taurus/5.1.1/bin/jmeter.sh', '-j', '/var/folders/9w/fj8tc51n59dgtrxfgskpxd9h0000gn/T/jmetertrgkjbrylog', '--version'] at .
[2019-04-08 12:42:37,347 DEBUG HTTPClient] Request resulted in exception: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gettaurus.org', port=443): Max retries exceeded with url: /updates/?version=1.13.4&installID=macos-3c075440e027 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='gettaurus.org', port=443): Max retries exceeded with url: /updates/?version=1.13.4&installID=macos-3c075440e027 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)'))

[2019-04-08 12:42:37,357 DEBUG Engine] Failed to check for updates: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gettaurus.org', port=443): Max retries exceeded with url: /updates/?version=1.13.4&installID=macos-3c075440e027 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='gettaurus.org', port=443): Max retries exceeded with url: /updates/?version=1.13.4&installID=macos-3c075440e027 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1120d9898>, 'Connection to gettaurus.org timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 695, in _check_updates
    response = client.request('GET', addr, timeout=10)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
bzt.TaurusNetworkError: Request to https://gettaurus.org/updates/?version=1.13.4&installID=macos-3c075440e027 failed

[2019-04-08 12:42:37,358 WARNING Engine] Failed to check for updates
[2019-04-08 12:42:41,825 DEBUG Engine.jmeter.JMeter] JMeter check:     _    ____   _    ____ _   _ _____       _ __  __ _____ _____ _____ ____     
   / \  |  _ \ / \  / ___| | | | ____|     | |  \/  | ____|_   _| ____|  _ \   
  / _ \ | |_) / _ \| |   | |_| |  _|    _  | | |\/| |  _|   | | |  _| | |_) | 
 / ___ \|  __/ ___ \ |___|  _  | |___  | |_| | |  | | |___  | | | |___|  _ <  
/_/   \_\_| /_/   \_\____|_| |_|_____|  \___/|_|  |_|_____| |_| |_____|_| \_\ 5.1.1 r1855137  

Copyright (c) 1999-2019 The Apache Software Foundation

 / 
[2019-04-08 12:42:41,830 DEBUG Engine.jmeter] Load: LoadSpec(concurrency=500, throughput=50.0, ramp_up=20.0, hold=10.0, iterations=0, duration=30.0, steps=None)
[2019-04-08 12:42:41,846 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/kpi.jtl
[2019-04-08 12:42:41,858 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/error.jtl
[2019-04-08 12:42:41,871 DEBUG Engine.jmeter.LoadSettingsProcessor.ThreadGroupHandler] Converting ThreadGroup (UserScenario) to ConcurrencyThreadGroup and apply load parameters
[2019-04-08 12:42:41,873 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
[2019-04-08 12:42:41,874 DEBUG JMX] Saving JMX to: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
[2019-04-08 12:42:41,879 DEBUG root] Executing shell: ['/Users/apple/.bzt/jmeter-taurus/5.1.1/bin/PluginsManagerCMD.sh', 'install-for-jmx', '/Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx'] at .
[2019-04-08 12:42:58,103 DEBUG Engine.jmeter.JMeter] Try to detect plugins for /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
2019-04-08 12:42:49,744 INFO o.j.r.PluginManagerCMD: Command is: install-for-jmx
2019-04-08 12:42:50,330 INFO o.j.r.JARSourceHTTP: Found cached repo
2019-04-08 12:42:52,178 INFO o.j.r.PluginManager: Plugins Status: [jpgc-functions=2.1, jpgc-casutg=2.8, jpgc-dummy=0.2, jpgc-ffw=2.0, jpgc-fifo=0.2, jpgc-json=2.7, jpgc-prmctl=0.4, jpgc-perfmon=2.1, jpgc-plugins-manager=1.3, jpgc-tst=2.5, jmeter-core=5.1.1, jmeter-ftp=5.1.1, jmeter-http=5.1.1, jmeter-jdbc=5.1.1, jmeter-jms=5.1.1, jmeter-junit=5.1.1, jmeter-java=5.1.1, jmeter-ldap=5.1.1, jmeter-mail=5.1.1, jmeter-mongodb=5.1.1, jmeter-native=5.1.1, jmeter-tcp=5.1.1, jmeter-components=5.1.1]
2019-04-08 12:42:52,231 INFO o.j.r.PluginManagerCMD: Params line is: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
2019-04-08 12:42:54,912 INFO o.a.j.s.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2
2019-04-08 12:42:55,121 INFO o.a.j.s.SaveService: Using SaveService properties file encoding UTF-8
2019-04-08 12:42:55,149 INFO o.a.j.s.SaveService: Using SaveService properties version 5.0
2019-04-08 12:42:55,498 INFO o.a.j.p.h.c.CacheManager: Will only cache the following methods: [GET]
2019-04-08 12:42:55,726 INFO o.a.j.p.h.c.CookieManager: Settings: Delete null: true Check: true Allow variable: true Save: false Prefix: COOKIE_
2019-04-08 12:42:56,690 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/html is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 12:42:56,831 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xhtml+xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 12:42:56,832 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for application/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 12:42:56,840 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/xml is org.apache.jmeter.protocol.http.parser.LagartoBasedHtmlParser
2019-04-08 12:42:56,842 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser
2019-04-08 12:42:56,857 INFO o.a.j.p.h.s.HTTPSamplerBase: Parser for text/css is org.apache.jmeter.protocol.http.parser.CssParser
2019-04-08 12:42:57,676 INFO o.j.r.PluginManager: Finishing without changes


[2019-04-08 12:42:58,109 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/jmeter.out
[2019-04-08 12:42:58,112 DEBUG Engine] New artifact filename: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/jmeter.err
[2019-04-08 12:42:58,125 DEBUG Engine] Module config: final-stats {'class': 'bzt.modules.reporting.FinalStatus'}
[2019-04-08 12:42:58,125 DEBUG root] Importing module: bzt.modules.reporting
[2019-04-08 12:42:58,212 DEBUG easyprocess] version=0.2.5
[2019-04-08 12:42:58,222 DEBUG pyvirtualdisplay] version=0.2.1
[2019-04-08 12:42:58,232 DEBUG root] Loading class: 'FinalStatus' from <module 'bzt.modules.reporting' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/reporting.py'>
[2019-04-08 12:42:58,233 DEBUG Engine] Module config: console {'class': 'bzt.modules.console.ConsoleStatusReporter'}
[2019-04-08 12:42:58,233 DEBUG root] Importing module: bzt.modules.console
[2019-04-08 12:42:58,234 DEBUG root] Loading class: 'ConsoleStatusReporter' from <module 'bzt.modules.console' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/console.py'>
[2019-04-08 12:42:58,235 WARNING Engine] Module 'console' can be only used once, will merge all new instances into single
[2019-04-08 12:42:58,237 DEBUG Engine] Module config: blazemeter {'class': 'bzt.modules.blazemeter.BlazeMeterUploader'}
[2019-04-08 12:42:58,237 DEBUG root] Importing module: bzt.modules.blazemeter
[2019-04-08 12:42:58,238 DEBUG root] Loading class: 'BlazeMeterUploader' from <module 'bzt.modules.blazemeter' from '/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py'>
[2019-04-08 12:42:58,553 WARNING Engine.blazemeter] No BlazeMeter API key provided, will upload anonymously
[2019-04-08 12:42:58,554 DEBUG Engine.blazemeter] Installing http client
[2019-04-08 12:42:58,555 DEBUG User] Request: GET https://a.blazemeter.com/api/v4/web/version None
[2019-04-08 12:42:58,556 DEBUG HTTPClient] Making HTTP request GET https://a.blazemeter.com/api/v4/web/version
[2019-04-08 12:42:58,636 DEBUG urllib3.connectionpool] Starting new HTTPS connection (1): a.blazemeter.com:443
[2019-04-08 12:43:05,988 DEBUG HTTPClient] Request resulted in exception: Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x113ce9438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='a.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/web/version (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x113ce9438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1143, in request
    return self.session.request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='a.blazemeter.com', port=443): Max retries exceeded with url: /api/v4/web/version (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x113ce9438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

[2019-04-08 12:43:05,989 ERROR root] Network Error: Request to https://a.blazemeter.com/api/v4/web/version failed
[2019-04-08 12:43:05,999 DEBUG root] TaurusNetworkError: Request to https://a.blazemeter.com/api/v4/web/version failed
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/cli.py", line 257, in perform
    self.engine.prepare()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 207, in prepare
    self.__prepare_reporters()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/engine.py", line 627, in __prepare_reporters
    module.prepare()
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/modules/blazemeter.py", line 248, in prepare
    self._user.ping()  # to check connectivity and auth
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 153, in ping
    self._request(self.address + '/api/v4/web/version')
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/bza.py", line 91, in _request
    response = self.http_request(method=log_method, url=url, data=data, headers=headers, timeout=self.timeout)
  File "/usr/local/Cellar/bzt/1.13.4/libexec/lib/python3.7/site-packages/bzt/utils.py", line 1150, in request
    raise TaurusNetworkError(msg)
[2019-04-08 12:43:05,999 INFO Engine] Post-processing...
[2019-04-08 12:43:06,000 DEBUG Engine.local] Post-process jmeter/UserScenario
[2019-04-08 12:43:06,000 DEBUG Engine] Add existing artifact (move=True): /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
[2019-04-08 12:43:06,001 DEBUG Engine] No need to copy /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/modified_requests.jmx
[2019-04-08 12:43:06,002 DEBUG Engine.jmeter.JTLErrorsReader.FileReader] File not appeared yet: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/error.jtl
[2019-04-08 12:43:06,002 DEBUG Engine.jmeter.JTLErrorsReader.FileReader] File not appeared yet: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/error.jtl
[2019-04-08 12:43:06,002 DEBUG Engine.jmeter.JTLReader.IncrementalCSVReader.FileReader] File not appeared yet: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/kpi.jtl
[2019-04-08 12:43:06,003 DEBUG Engine.jmeter.JTLReader] Buffer len: 0; Known errors count: 0
[2019-04-08 12:43:06,003 DEBUG Engine.consolidator] Consolidator buffer[0]: dict_keys([])
[2019-04-08 12:43:06,015 INFO Engine.final-stats] Test duration: 0:00:00
[2019-04-08 12:43:06,018 DEBUG Engine.console] No logger_handler or orig_stream was detected
[2019-04-08 12:43:06,018 DEBUG Engine.blazemeter] No feeding session obtained, nothing to finalize
[2019-04-08 12:43:06,030 DEBUG Engine.Configuration] Dumping YAML config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/effective.yml
[2019-04-08 12:43:06,876 DEBUG Engine.Configuration] Dumping JSON config into /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/effective.json
[2019-04-08 12:43:06,883 INFO root] Artifacts dir: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840
[2019-04-08 12:43:06,888 WARNING root] Done performing with code: 1
[2019-04-08 12:43:06,889 DEBUG root] Closing log handler: /Users/apple/Desktop/bachelorProject/stressThing/StressThing/2019-04-08_12-42-27.273840/bzt.log
